<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuratKeluarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('surat_keluar')->insert([
            [
                'nomor_urut' => 1,
                'nomor_berkas' => '001/789',
                'alamat_penerima' => 'Kantor Bupati Banjarbaru',
                'tanggal_surat' => '2025-10-01',
                'perihal' => 'Permohonan Bantuan Dana Operasional',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 2,
                'nomor_berkas' => '002/789',
                'alamat_penerima' => 'Dinas Pendidikan Provinsi Kalsel',
                'tanggal_surat' => '2025-10-03',
                'perihal' => 'Laporan Kegiatan Bulanan',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 3,
                'nomor_berkas' => '003/789',
                'alamat_penerima' => 'Universitas Lambung Mangkurat',
                'tanggal_surat' => '2025-10-05',
                'perihal' => 'Undangan Seminar Nasional',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 4,
                'nomor_berkas' => '004/789',
                'alamat_penerima' => 'PT. PLN (Persero) Wilayah Kalsel',
                'tanggal_surat' => '2025-10-07',
                'perihal' => 'Permohonan Penambahan Daya Listrik',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 5,
                'nomor_berkas' => '005/789',
                'alamat_penerima' => 'Kepala Desa Sungai Tabuk',
                'tanggal_surat' => '2025-10-10',
                'perihal' => 'Pemberitahuan Program Desa Mandiri',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 6,
                'nomor_berkas' => '006/789',
                'alamat_penerima' => 'Yayasan Pendidikan Anak Bangsa',
                'tanggal_surat' => '2025-10-12',
                'perihal' => 'Proposal Kerjasama Pendidikan',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 7,
                'nomor_berkas' => '007/789',
                'alamat_penerima' => 'RSUD Abdul Aziz Banjarbaru',
                'tanggal_surat' => '2025-10-15',
                'perihal' => 'Permohonan Dukungan Medis',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 8,
                'nomor_berkas' => '008/789',
                'alamat_penerima' => 'Kantor Pos Indonesia Cabang Banjarbaru',
                'tanggal_surat' => '2025-10-18',
                'perihal' => 'Permohonan Pengiriman Dokumen Penting',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 9,
                'nomor_berkas' => '009/789',
                'alamat_penerima' => 'Dinas Perhubungan Kota Banjarbaru',
                'tanggal_surat' => '2025-10-20',
                'perihal' => 'Laporan Kondisi Jalan',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 10,
                'nomor_berkas' => '010/789',
                'alamat_penerima' => 'Kepala UPTD Taman Hutan Raya',
                'tanggal_surat' => '2025-10-22',
                'perihal' => 'Permohonan Izin Kunjungan Lapangan',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 11,
                'nomor_berkas' => '011/789',
                'alamat_penerima' => 'Kantor Camat Landasan Ulin',
                'tanggal_surat' => '2025-10-25',
                'perihal' => 'Laporan Kegiatan Sosial Kemasyarakatan',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 12,
                'nomor_berkas' => '012/789',
                'alamat_penerima' => 'Dinas Lingkungan Hidup',
                'tanggal_surat' => '2025-10-27',
                'perihal' => 'Laporan Pemantauan Kualitas Udara',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 13,
                'nomor_berkas' => '013/789',
                'alamat_penerima' => 'Kepala SD Negeri 01 Banjarbaru',
                'tanggal_surat' => '2025-10-29',
                'perihal' => 'Permohonan Bantuan Alat Peraga',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 14,
                'nomor_berkas' => '014/789',
                'alamat_penerima' => 'Kantor Notaris & PPAT',
                'tanggal_surat' => '2025-11-01',
                'perihal' => 'Permohonan Legalisasi Dokumen',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 15,
                'nomor_berkas' => '015/789',
                'alamat_penerima' => 'PT. Bank BRI Cabang Banjarbaru',
                'tanggal_surat' => '2025-11-03',
                'perihal' => 'Permohonan Rekening Baru',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 16,
                'nomor_berkas' => '016/789',
                'alamat_penerima' => 'Kepala SMP Negeri 02 Banjarbaru',
                'tanggal_surat' => '2025-11-05',
                'perihal' => 'Undangan Rapat Koordinasi Guru',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 17,
                'nomor_berkas' => '017/789',
                'alamat_penerima' => 'Dinas Kesehatan Kabupaten Banjar',
                'tanggal_surat' => '2025-11-08',
                'perihal' => 'Laporan Stok Obat',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 18,
                'nomor_berkas' => '018/789',
                'alamat_penerima' => 'Kantor Imigrasi Kelas I Banjarbaru',
                'tanggal_surat' => '2025-11-10',
                'perihal' => 'Permohonan Informasi Visa',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 19,
                'nomor_berkas' => '019/789',
                'alamat_penerima' => 'Kepala SMK Negeri 01 Banjarbaru',
                'tanggal_surat' => '2025-11-12',
                'perihal' => 'Permohonan Bantuan Praktik Kerja Industri',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_urut' => 20,
                'nomor_berkas' => '020/789',
                'alamat_penerima' => 'Dinas Komunikasi dan Informatika',
                'tanggal_surat' => '2025-11-15',
                'perihal' => 'Permohonan Akses Server Lokal',
                'nomor_petunjuk' => null,
                'nomor_paket' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}